//// ------------------------------------------------------------------------------
////  <auto-generated>
////      This code was generated by SpecFlow (http://www.specflow.org/).
////      SpecFlow Version:1.9.3.0
////      SpecFlow Generator Version:1.9.0.0
////      Runtime Version:4.0.30319.18444
//// 
////      Changes to this file may cause incorrect behavior and will be lost if
////      the code is regenerated.
////  </auto-generated>
//// ------------------------------------------------------------------------------
//#region Designer generated code
//#pragma warning disable
//namespace Warewolf.AcceptanceTesting.EmailSource
//{
//    using TechTalk.SpecFlow;
    
    
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.3.0")]
//    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
//    [NUnit.Framework.TestFixtureAttribute()]
//    [NUnit.Framework.DescriptionAttribute("Email Source")]
//    public partial class EmailSourceFeature
//    {
        
//        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
//#line 1 "Email Source.feature"
//#line hidden
        
//        [NUnit.Framework.TestFixtureSetUpAttribute()]
//        public virtual void FeatureSetup()
//        {
//            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
//            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Email Source", "In order to share settings\nI want to save my Email source Settings\nSo that I can " +
//                    "reuse them", ProgrammingLanguage.CSharp, ((string[])(null)));
//            testRunner.OnFeatureStart(featureInfo);
//        }
        
//        [NUnit.Framework.TestFixtureTearDownAttribute()]
//        public virtual void FeatureTearDown()
//        {
//            testRunner.OnFeatureEnd();
//            testRunner = null;
//        }
        
//        [NUnit.Framework.SetUpAttribute()]
//        public virtual void TestInitialize()
//        {
//        }
        
//        [NUnit.Framework.TearDownAttribute()]
//        public virtual void ScenarioTearDown()
//        {
//            testRunner.OnScenarioEnd();
//        }
        
//        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
//        {
//            testRunner.OnScenarioStart(scenarioInfo);
//        }
        
//        public virtual void ScenarioCleanup()
//        {
//            testRunner.CollectScenarioErrors();
//        }
//    }
//}
//#pragma warning restore
//#endregion
